# Configuración de Base de Datos para Supabase (PostgreSQL)
# =========================================================

# Conexión PostgreSQL (Supabase Pooler)
db.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require
db.user=postgres.ibngomeyrgghgvgbkgqf
db.password=YXCn*mB6V@BXb+$

# Driver PostgreSQL
db.driver=org.postgresql.Driver

# Parámetros opcionales
db.pool.size=10
db.connection.timeout=30000
